export const technologiestiftungRules = {
  files: ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx"],
  languageOptions: {
    globals: {
      React: "readonly",
    },
  },
  rules: {
    "prefer-const": "error",
    curly: "error",
    "no-console": ["error", { allow: ["warn", "error"] }],
    "no-undef": "error",
    "no-var": "error",
    "default-case": ["error", { commentPattern: "^no default$" }],
    "arrow-parens": "error",
    "consistent-return": "error",
    "default-param-last": ["error"],
    eqeqeq: "error",
    "max-depth": ["error", 4],
    "max-params": ["error", 3],
    complexity: ["error", 10],
    "new-cap": [
      "error",
      {
        newIsCap: true,
        capIsNew: false,
        properties: false,
      },
    ],
    "no-else-return": "error",
    "no-eval": "error",
    "no-implicit-globals": "error",
    "no-lonely-if": "error",
    "no-loop-func": "error",
    "no-multi-assign": "error",
    "no-multi-str": "error",
    "no-nested-ternary": "error",
    "no-new": "error",
    "no-param-reassign": "error",
    "no-return-assign": "error",
    "no-shadow": "error",
    "no-throw-literal": "error",
    "no-unneeded-ternary": "error",
    "@typescript-eslint/no-unused-vars": [
      "error",
      {
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
      },
    ],
  },
};
