/* eslint-disable @typescript-eslint/no-explicit-any */
import type { Meta, StoryObj } from "@storybook/react";
import { Icon } from "./Icon";

const meta: Meta<typeof Icon> = {
	title: "Elements/Icon",
	component: Icon,
	parameters: {
		layout: "centered",
	},
	tags: ["autodocs"],
	argTypes: {
		name: {
			control: "select",
			options: [
				"arrow-down",
				"arrow-left",
				"arrow-right",
				"arrow-up",
				"bars",
				"calendar",
				"cart",
				"check-circle",
				"chevron-down",
				"chevron-right",
				"chevron-up",
				"circle-down",
				"clock",
				"clock-circle",
				"close",
				"comment",
				"comment-dots",
				"comments",
				"desktop",
				"dgs",
				"download",
				"edit",
				"envelope",
				"error",
				"euro-sign",
				"external-link",
				"facebook",
				"fax",
				"filter",
				"flickr",
				"heart",
				"info",
				"info-circle",
				"instagram",
				"landmark",
				"leichte-sprache",
				"link",
				"lock",
				"lock-open",
				"login",
				"logout",
				"map",
				"map-marker",
				"mobile",
				"pause",
				"phone",
				"pinterest",
				"play",
				"print",
				"quote-left",
				"right",
				"rss",
				"search",
				"seeding",
				"snapchat",
				"square-bluesky",
				"square-facebook",
				"square-instagram",
				"square-linkedin",
				"square-threads",
				"square-x-twitter",
				"square-xing",
				"square-youtube",
				"star",
				"star-half-stroke",
				"star-solid",
				"success",
				"tablet",
				"threads",
				"ticket",
				"times",
				"times-circle",
				"trash",
				"twitter",
				"universal-access",
				"user",
				"user-check",
				"whatsapp",
				"x",
				"x-twitter",
			],
		},
		className: {
			control: "text",
		},
	},
};

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
	args: {
		name: "search",
	},
};

export const WithCustomSize: Story = {
	args: {
		name: "star",
		className: "w-8 h-8 text-yellow-500",
	},
};

export const IconGallery: Story = {
	render: () => (
		<div className="grid max-w-6xl grid-cols-8 gap-4 p-4">
			{[
				"arrow-down",
				"arrow-left",
				"arrow-right",
				"arrow-up",
				"bars",
				"calendar",
				"cart",
				"check-circle",
				"chevron-down",
				"chevron-right",
				"chevron-up",
				"circle-down",
				"clock",
				"clock-circle",
				"close",
				"comment",
				"comment-dots",
				"comments",
				"desktop",
				"dgs",
				"download",
				"edit",
				"envelope",
				"error",
				"euro-sign",
				"external-link",
				"facebook",
				"fax",
				"filter",
				"flickr",
				"heart",
				"info",
				"info-circle",
				"instagram",
				"landmark",
				"leichte-sprache",
				"link",
				"lock",
				"lock-open",
				"login",
				"logout",
				"map",
				"map-marker",
				"mobile",
				"pause",
				"phone",
				"pinterest",
				"play",
				"print",
				"quote-left",
				"right",
				"rss",
				"search",
				"seeding",
				"snapchat",
				"square-bluesky",
				"square-facebook",
				"square-instagram",
				"square-linkedin",
				"square-threads",
				"square-x-twitter",
				"square-xing",
				"square-youtube",
				"star",
				"star-half-stroke",
				"star-solid",
				"success",
				"tablet",
				"threads",
				"ticket",
				"times",
				"times-circle",
				"trash",
				"twitter",
				"universal-access",
				"user",
				"user-check",
				"whatsapp",
				"x",
				"x-twitter",
			].map((iconName) => (
				<div key={iconName} className="flex flex-col items-center gap-2 p-2">
					<Icon name={iconName as any} className="size-6 text-gray-700" />
					<span className="text-center text-xs break-words text-gray-600">
						{iconName}
					</span>
				</div>
			))}
		</div>
	),
};
